<a href="https://colab.research.google.com/github/1cg16is044/internship/blob/master/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Linear *Algebra*

Simple Array Operations

In [0]:
import numpy as np
a=np.array([[1.0,2.0],[3.0,4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


In [0]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [0]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [0]:
u = np.eye(2)
u

array([[1., 0.],
       [0., 1.]])

In [0]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])
j@j


array([[-1.,  0.],
       [ 0., -1.]])

In [0]:
np.trace(u)

2.0

In [0]:
y = np.array([[5.], [7.]])
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [0]:
np.linalg.eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

Python array examples

In [0]:
from array import *
my_array=array('i',[1,2,3,4,5])
for i in my_array:
  print(i)

1
2
3
4
5


In [0]:
my_array[1]

2

In [0]:
my_array[2]

3

In [0]:
my_array[0]

1

In [0]:
my_array.append(6)
my_array

array('i', [1, 2, 3, 4, 5, 6])

In [0]:
my_array.append(7)
my_array

array('i', [1, 2, 3, 4, 5, 6, 7])

In [0]:
my_array.insert(0,0)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7])

In [0]:
my_array.insert(8,8)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8])

In [0]:
my_extend_array=array('i',[7,8,9,10])
my_array.extend(my_extend_array)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 7, 8, 9, 10])

In [0]:
c=[11,12,13]
my_array.fromlist(c)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 7, 8, 9, 10, 11, 12, 13])

In [0]:
my_array.remove(13)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 7, 8, 9, 10, 11, 12])

In [0]:
my_array.remove(11)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 7, 8, 9, 10, 12])

In [0]:
my_array.remove(8)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 7])

In [0]:
my_array.pop()

7

In [0]:
my_array.index(3)

3

In [0]:
my_array.reverse()
my_array

array('i', [7, 6, 5, 4, 3, 2, 1, 0])

In [0]:
my_array.buffer_info()

(140429863120944, 8)

In [0]:
my_array.count(7)

1

In [0]:
my_char_array=array('i',[ord('g'),ord('e'),ord('e'),ord('k')])
my_char_array

array('i', [103, 101, 101, 107])

In [0]:
c=my_array.tolist()
c

[7, 6, 5, 4, 3, 2, 1, 0]

Prime number generator

In [0]:
def is_prime(n):
    for i in range(2, n):
        if n % i == 0:
             return False
    return True
n = input("Enter a number: ")
for x in range(2, int(n)):
    if is_prime(x):
         print(x, " is prime")
    else:
        print(x, " is not prime")

Enter a number: 12
2  is prime
3  is prime
4  is not prime
5  is prime
6  is not prime
7  is prime
8  is not prime
9  is not prime
10  is not prime
11  is prime


In [56]:
n=input("enter a number:")
#for x in int(n):
if is_prime(int(n)):
         print(n,"is prime")
else:
         print(n,"is not prime")

enter a number:2
2 is prime


In [60]:
start=1
end=100
for nume in range(start,end+1):
    if nume % 2 == 0:
        print(nume, end=" ")

2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98 100 