<a href="https://colab.research.google.com/github/1cg16is044/internship/blob/master/np1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
a=np.arange(18).reshape(2,3,3)
a


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [0]:
a.shape

(3, 5)

In [0]:
a.ndim

3

In [0]:
a.dtype.name

'int64'

In [0]:
a.itemsize


8

In [0]:
a.size

18

In [0]:
type(a)

numpy.ndarray

In [0]:
b=np.array([678])
b

array([678])

In [0]:
type(b)

numpy.ndarray

Array creation

In [0]:
import numpy as np
a=np.array([234])
a

array([234])

In [0]:
a.dtype

dtype('int64')

In [0]:
b=np.array([1.2,3.5,5.1])
b.dtype

dtype('float64')

In [0]:
b=np.array([(1.5,2,3),(4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [0]:
c=np.array([[1,2],[3,4]],dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [0]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [0]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [0]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [0]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [0]:
from numpy import pi
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [0]:
x=np.linspace(0,2*pi,100)
f=np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

Printing Arrays

In [0]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [0]:
b=np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [0]:
c=np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [0]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [0]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


Basic operations

In [0]:
a=np.array([20,30,40,50])

In [0]:
b=np.arange(4)


In [0]:
b

array([0, 1, 2, 3])

In [0]:
c=a-b
c

array([20, 29, 38, 47])

In [0]:
b**2

array([0, 1, 4, 9])

In [0]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [0]:
a<35

array([ True,  True, False, False])

In [0]:
a=np.array([[1,1],[0,1]])
b=np.array([[2,0],[3,4]])
a*b

array([[2, 0],
       [0, 4]])

In [0]:
a@b

array([[5, 4],
       [3, 4]])

In [0]:
a.dot(b)

array([[5, 4],
       [3, 4]])

In [0]:
a=np.ones((2,3),dtype=int)
b=np.random.random((2,3))
a*=3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [0]:
b+=a
b

array([[3.88421737, 3.30140101, 3.65395337],
       [3.85790373, 3.86450936, 3.98025742]])

In [0]:
a=np.ones(3,dtype=np.int32)
b=np.linspace(0,pi,3)
b.dtype.name

'float64'

In [0]:
c=a+b
c

array([1.        , 2.57079633, 4.14159265])

In [0]:
c.dtype.name

'float64'

In [0]:
d=np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [0]:
d.dtype.name

'complex128'

In [0]:
a=np.random.random((2,3))
a

array([[0.5630756 , 0.34912863, 0.38533643],
       [0.52808336, 0.40768589, 0.15227154]])

In [0]:
a.sum()

2.385581444389563

In [0]:
a.min()

0.15227153696692153

In [0]:
a.max()

0.5630755984681881

Universal Functions

In [0]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [0]:
b.min(axis=1)

array([0, 4, 8])

In [0]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

Indexing,slicing and iterating


In [3]:
import numpy as np
a= np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [4]:
a[2]

8