<a href="https://colab.research.google.com/github/1cg16is044/internship/blob/master/np1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
a=np.arange(18).reshape(2,3,3)
a


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [3]:
a.shape

(3, 5)

In [12]:
a.ndim

3

In [13]:
a.dtype.name

'int64'

In [15]:
a.itemsize


8

In [16]:
a.size

18

In [17]:
type(a)

numpy.ndarray

In [18]:
b=np.array([678])
b

array([678])

In [19]:
type(b)

numpy.ndarray

In [20]:
import numpy as np
a=np.array([234])
a

array([234])

In [21]:
a.dtype

dtype('int64')

In [22]:
b=np.array([1.2,3.5,5.1])
b.dtype

dtype('float64')

In [23]:
b=np.array([(1.5,2,3),(4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [24]:
c=np.array([[1,2],[3,4]],dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [30]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [31]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [32]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [0]:
from